# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/elysia/Software/Xilinx/Project/11-6/2023D_lwx.srcs/sources_1/ip/fir_lpf_fsk/fir_lpf_fsk.xci
# IP: The module: 'fir_lpf_fsk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/elysia/Software/Xilinx/Project/11-6/2023D_lwx.gen/sources_1/ip/fir_lpf_fsk/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_lpf_fsk'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/elysia/Software/Xilinx/Project/11-6/2023D_lwx.gen/sources_1/ip/fir_lpf_fsk/fir_lpf_fsk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_lpf_fsk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/elysia/Software/Xilinx/Project/11-6/2023D_lwx.srcs/sources_1/ip/fir_lpf_fsk/fir_lpf_fsk.xci
# IP: The module: 'fir_lpf_fsk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/elysia/Software/Xilinx/Project/11-6/2023D_lwx.gen/sources_1/ip/fir_lpf_fsk/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_lpf_fsk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/elysia/Software/Xilinx/Project/11-6/2023D_lwx.gen/sources_1/ip/fir_lpf_fsk/fir_lpf_fsk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_lpf_fsk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
