# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/elysia/Software/Xilinx/Project/11-6/2023D_lwx.srcs/sources_1/bd/design_1/ip/design_1_IQ_DDC_0_0/design_1_IQ_DDC_0_0.xci
# IP: The module: 'design_1_IQ_DDC_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/elysia/Software/Xilinx/Project/11-6/2023D_lwx.srcs/sources_1/ip/cic_compiler_iq/cic_compiler_iq.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cic_compiler_iq || ORIG_REF_NAME==cic_compiler_iq} -quiet] -quiet

# XDC: /home/elysia/Software/Xilinx/Project/11-6/2023D_lwx.gen/sources_1/bd/design_1/ip/design_1_IQ_DDC_0_0/design_1_IQ_DDC_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_IQ_DDC_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/elysia/Software/Xilinx/Project/11-6/2023D_lwx.srcs/sources_1/bd/design_1/ip/design_1_IQ_DDC_0_0/design_1_IQ_DDC_0_0.xci
# IP: The module: 'design_1_IQ_DDC_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/elysia/Software/Xilinx/Project/11-6/2023D_lwx.srcs/sources_1/ip/cic_compiler_iq/cic_compiler_iq.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cic_compiler_iq || ORIG_REF_NAME==cic_compiler_iq} -quiet] -quiet

# XDC: /home/elysia/Software/Xilinx/Project/11-6/2023D_lwx.gen/sources_1/bd/design_1/ip/design_1_IQ_DDC_0_0/design_1_IQ_DDC_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_IQ_DDC_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
