# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/elysia/Software/Xilinx/Project/11-6V3/2023D_lwx.srcs/sources_1/bd/design_1/ip/design_1_PSK_DM_0_0/design_1_PSK_DM_0_0.xci
# IP: The module: 'design_1_PSK_DM_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/elysia/Software/Xilinx/Project/11-6V3/2023D_lwx.srcs/sources_1/ip/fir_lpf_psk/fir_lpf_psk.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_lpf_psk || ORIG_REF_NAME==fir_lpf_psk} -quiet] -quiet

# IP: /home/elysia/Software/Xilinx/Project/11-6V3/2023D_lwx.srcs/sources_1/ip/mult_gen_psk/mult_gen_psk.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_gen_psk || ORIG_REF_NAME==mult_gen_psk} -quiet] -quiet

# XDC: /home/elysia/Software/Xilinx/Project/11-6V3/2023D_lwx.gen/sources_1/bd/design_1/ip/design_1_PSK_DM_0_0/design_1_PSK_DM_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_PSK_DM_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/elysia/Software/Xilinx/Project/11-6V3/2023D_lwx.srcs/sources_1/bd/design_1/ip/design_1_PSK_DM_0_0/design_1_PSK_DM_0_0.xci
# IP: The module: 'design_1_PSK_DM_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/elysia/Software/Xilinx/Project/11-6V3/2023D_lwx.srcs/sources_1/ip/fir_lpf_psk/fir_lpf_psk.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_lpf_psk || ORIG_REF_NAME==fir_lpf_psk} -quiet] -quiet

# IP: /home/elysia/Software/Xilinx/Project/11-6V3/2023D_lwx.srcs/sources_1/ip/mult_gen_psk/mult_gen_psk.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_gen_psk || ORIG_REF_NAME==mult_gen_psk} -quiet] -quiet

# XDC: /home/elysia/Software/Xilinx/Project/11-6V3/2023D_lwx.gen/sources_1/bd/design_1/ip/design_1_PSK_DM_0_0/design_1_PSK_DM_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_PSK_DM_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
