# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/elysia/Software/Xilinx/Project/11-6/2023D_lwx.srcs/sources_1/ip/cic_compiler_iq/cic_compiler_iq.xci
# IP: The module: 'cic_compiler_iq' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/elysia/Software/Xilinx/Project/11-6/2023D_lwx.gen/sources_1/ip/cic_compiler_iq/cic_compiler_iq_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cic_compiler_iq'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/elysia/Software/Xilinx/Project/11-6/2023D_lwx.srcs/sources_1/ip/cic_compiler_iq/cic_compiler_iq.xci
# IP: The module: 'cic_compiler_iq' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/elysia/Software/Xilinx/Project/11-6/2023D_lwx.gen/sources_1/ip/cic_compiler_iq/cic_compiler_iq_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cic_compiler_iq'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
