# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/elysia/Software/Xilinx/Project/11-6/2023D_lwx.srcs/sources_1/ip/mult_gen_psk/mult_gen_psk.xci
# IP: The module: 'mult_gen_psk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/elysia/Software/Xilinx/Project/11-6/2023D_lwx.gen/sources_1/ip/mult_gen_psk/mult_gen_psk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_gen_psk'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/elysia/Software/Xilinx/Project/11-6/2023D_lwx.srcs/sources_1/ip/mult_gen_psk/mult_gen_psk.xci
# IP: The module: 'mult_gen_psk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/elysia/Software/Xilinx/Project/11-6/2023D_lwx.gen/sources_1/ip/mult_gen_psk/mult_gen_psk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_gen_psk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
