# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/elysia/Software/Xilinx/Project/11-6/2023D_lwx.srcs/sources_1/bd/design_1/ip/design_1_FSK_DM_0_0/design_1_FSK_DM_0_0.xci
# IP: The module: 'design_1_FSK_DM_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/elysia/Software/Xilinx/Project/11-6/2023D_lwx.srcs/sources_1/ip/fir_lpf_fsk/fir_lpf_fsk.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_lpf_fsk || ORIG_REF_NAME==fir_lpf_fsk} -quiet] -quiet

# IP: /home/elysia/Software/Xilinx/Project/11-6/2023D_lwx.srcs/sources_1/ip/cordic_atan4/cordic_atan4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cordic_atan4 || ORIG_REF_NAME==cordic_atan4} -quiet] -quiet

# XDC: /home/elysia/Software/Xilinx/Project/11-6/2023D_lwx.gen/sources_1/bd/design_1/ip/design_1_FSK_DM_0_0/design_1_FSK_DM_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_FSK_DM_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/elysia/Software/Xilinx/Project/11-6/2023D_lwx.srcs/sources_1/bd/design_1/ip/design_1_FSK_DM_0_0/design_1_FSK_DM_0_0.xci
# IP: The module: 'design_1_FSK_DM_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/elysia/Software/Xilinx/Project/11-6/2023D_lwx.srcs/sources_1/ip/fir_lpf_fsk/fir_lpf_fsk.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_lpf_fsk || ORIG_REF_NAME==fir_lpf_fsk} -quiet] -quiet

# IP: /home/elysia/Software/Xilinx/Project/11-6/2023D_lwx.srcs/sources_1/ip/cordic_atan4/cordic_atan4.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cordic_atan4 || ORIG_REF_NAME==cordic_atan4} -quiet] -quiet

# XDC: /home/elysia/Software/Xilinx/Project/11-6/2023D_lwx.gen/sources_1/bd/design_1/ip/design_1_FSK_DM_0_0/design_1_FSK_DM_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_FSK_DM_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
