# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PIN.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_PSK_DM_0_0/design_1_PSK_DM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_PSK_DM_0_0 || ORIG_REF_NAME==design_1_PSK_DM_0_0} -quiet] -quiet

# IP: ip/fir_lpf_psk/fir_lpf_psk.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_lpf_psk || ORIG_REF_NAME==fir_lpf_psk} -quiet] -quiet

# IP: ip/mult_gen_psk/mult_gen_psk.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_gen_psk || ORIG_REF_NAME==mult_gen_psk} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FSK_DM_0_0/design_1_FSK_DM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FSK_DM_0_0 || ORIG_REF_NAME==design_1_FSK_DM_0_0} -quiet] -quiet

# IP: ip/fir_lpf_fsk/fir_lpf_fsk.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_lpf_fsk || ORIG_REF_NAME==fir_lpf_fsk} -quiet] -quiet

# IP: ip/cordic_atan4/cordic_atan4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cordic_atan4 || ORIG_REF_NAME==cordic_atan4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ADC_3PA1030_0_1/design_1_ADC_3PA1030_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ADC_3PA1030_0_1 || ORIG_REF_NAME==design_1_ADC_3PA1030_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_IQ_DDC_0_0/design_1_IQ_DDC_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_IQ_DDC_0_0 || ORIG_REF_NAME==design_1_IQ_DDC_0_0} -quiet] -quiet

# IP: ip/cic_compiler_iq/cic_compiler_iq.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cic_compiler_iq || ORIG_REF_NAME==cic_compiler_iq} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_0/design_1_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_0 || ORIG_REF_NAME==design_1_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ASK_DM_0_2/design_1_ASK_DM_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ASK_DM_0_2 || ORIG_REF_NAME==design_1_ASK_DM_0_2} -quiet] -quiet

# IP: ip/cordic_ask/cordic_ask.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cordic_ask || ORIG_REF_NAME==cordic_ask} -quiet] -quiet

# IP: bd/design_1/ip/design_1_waveform_measure_0_0/design_1_waveform_measure_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_waveform_measure_0_0 || ORIG_REF_NAME==design_1_waveform_measure_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_waveform_measure_0_1/design_1_waveform_measure_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_waveform_measure_0_1 || ORIG_REF_NAME==design_1_waveform_measure_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_DAC_904_0_0/design_1_DAC_904_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_DAC_904_0_0 || ORIG_REF_NAME==design_1_DAC_904_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_data_select_0_0/design_1_data_select_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_data_select_0_0 || ORIG_REF_NAME==design_1_data_select_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_waveform_measure_0_2/design_1_waveform_measure_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_waveform_measure_0_2 || ORIG_REF_NAME==design_1_waveform_measure_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_ask_0_0/design_1_axi_gpio_ask_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_ask_0_0 || ORIG_REF_NAME==design_1_axi_gpio_ask_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_ask_0_1/design_1_axi_gpio_ask_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_ask_0_1 || ORIG_REF_NAME==design_1_axi_gpio_ask_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_ask_0_2/design_1_axi_gpio_ask_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_ask_0_2 || ORIG_REF_NAME==design_1_axi_gpio_ask_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_ask_0_3/design_1_axi_gpio_ask_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_ask_0_3 || ORIG_REF_NAME==design_1_axi_gpio_ask_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_50M_0/design_1_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_1 || ORIG_REF_NAME==design_1_axi_gpio_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_2/design_1_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_2 || ORIG_REF_NAME==design_1_axi_gpio_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_1/design_1_axi_smc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_smc_1 || ORIG_REF_NAME==design_1_axi_smc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ila_0_0/design_1_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ila_0_0 || ORIG_REF_NAME==design_1_ila_0_0} -quiet] -quiet

# XDC: /home/elysia/Software/Xilinx/Project/11-6V3/2023D_lwx.gen/sources_1/bd/design_1/design_1_ooc.xdc
